Repository Team-DragMe/DragMe-Client, pull requests merged in 2022-07, with the labels that each got.

#14 [#8] 오늘 하루 계획 컴포넌트 제작
  package.json
  public/assets/icons/ActiveAddon.svg
  public/assets/icons/Addon.svg
  public/assets/icons/DownArrow.svg
  public/assets/icons/PlusBtn.svg
  public/assets/icons/RightArrow.svg
  public/assets/icons/SemiArrow.svg
  public/assets/icons/SemiArrow2.svg
  public/assets/icons/checkIcon.svg
  public/assets/icons/checkIconActive.svg
  src/components/Day/MainDayPlanList.tsx
  src/components/Day/Reschedule.tsx
  src/components/common/.keep
  src/components/common/AddonBtn.tsx
  src/components/common/CheckBox.tsx
  src/components/common/CollapseArrow.tsx
  src/components/common/DayPlanChip/AddDayPlanChip.tsx
  src/components/common/DayPlanChip/CommonDayPlanChip.tsx
  src/components/common/DayPlanList/DayPlan.tsx
  src/components/common/DayPlanList/DayPlanList.tsx
  src/components/common/DayPlanList/SubDayPlanList.tsx
  src/components/common/RoutineBox/index.tsx
  src/lib/api/.keep
  src/lib/style/animation.ts
  src/mock-data/schedules.ts
Labels: :sparkles: feature, :gun: 리뷰중, 나희

#15 [#5] 오늘 하루 계획 다짐 및 하루 노트 컴포넌트 제작
  .eslintrc.json
  .stylelintrc.json
  package.json
  public/assets/SmileEmoticon.png
  src/components/Day/TodayNote/index.tsx
  src/components/Day/TodayPlan/EmojiPicker.tsx
  src/components/Day/TodayPlan/TodayPlanInput.tsx
  src/components/Day/TodayPlan/index.tsx
  src/hooks/useDebouncing.tsx
  src/pages/day/[date].tsx
  src/pages/index.tsx
Labels: :sparkles: feature, :gun: 리뷰중, 유림

#26 [#24][FEATURE] #A-13 계획블록 더보기 모달 구현
  public/assets/icon_doubleArrow.png
  public/assets/icon_trashCan.png
  src/components/Day/DayPlanSettingModal.tsx
  src/components/common/NavBar.tsx
  src/pages/_document.tsx
  src/pages/day/[date].tsx
  src/styles/theme.ts
Labels: :sparkles: feature, :gun: 리뷰중, 남준

#28 [#20][FEATURE] #A-9 일정 등록 모달 구현
  public/assets/DeleteButton.svg
  public/assets/ToggleButton.svg
  src/components/Day/DayPlanModal/ColorListModal.tsx
  src/components/Day/DayPlanModal/ColorPicker.tsx
  src/components/Day/DayPlanModal/DayPlanTitle.tsx
  src/components/Day/DayPlanModal/SubPlanBox.tsx
  src/components/Day/DayPlanModal/SubPlanTitle.tsx
  src/components/Day/DayPlanModal/SubPlanTitleButton.tsx
  src/components/Day/DayPlanModal/index.tsx
Labels: :sparkles: feature, :gun: 리뷰중, 유림

#32 [#31][FEATURE] #B-5 Monthly Goal 컴포넌트 제작
  src/components/Week/MonthlyGoal/MonthlyGoalBox.tsx
  src/components/Week/MonthlyGoal/MonthlyGoalInput.tsx
  src/components/Week/MonthlyGoal/index.tsx
Labels: :sparkles: feature, 유림

#33 [#27,29][FEATURE] #B-3,C-1 주간 계획 섹션 카드 제작, axios 세팅 및 캘린더 api 연결
  src/components/Day/DayInfoSection/DayChange.tsx
  src/components/Day/Modal/CalendarModal.tsx
  src/components/Day/TodayPlan/EmojiPicker.tsx
  src/components/Day/TodayPlan/index.tsx
  src/components/Week/WeekPlan/WeekPlanCard.tsx
  src/hooks/query/useCalendarData.tsx
  src/lib/api/api.ts
  src/lib/api/dayApi.ts
  src/pages/_app.tsx
  src/pages/day/[date].tsx
  src/pages/index.tsx
  src/pages/mypage.tsx
  src/pages/week/.keep
  src/pages/week/[week].tsx
  src/types/.keep
  src/types/day.ts
  src/utils/dateUtil.ts
  yarn.lock
Labels: :sparkles: feature, 희선

#35 [#23][Feature] #B-1 Feature 주간 날짜 정보 박스 컴포넌트 제작
  src/components/Week/WeekChange.tsx
  src/components/Week/WeekInfo.tsx
  src/components/common/NavBar.tsx
  src/states/index.ts
  src/utils/getWeek.ts
Labels: :sparkles: feature, 남준

#36 [#23][FEATURE] #B-1 날짜박스 컴포넌트 제작
  src/components/Week/WeekChange.tsx
  src/components/Week/WeekInfo.tsx
  src/utils/getWeek.ts
Labels: :sparkles: feature, 남준

#40 [#38][FEATURE] #C-3 주간 목표 조회 api 연결
  src/components/Week/WeeklyGoal/WeeklyGoalBox.tsx
  src/hooks/query/useGetWeeklyGoalData.tsx
  src/lib/api/.keep
  src/lib/api/weekApi.ts
  src/types/week.ts
Labels: :sparkles: feature, 희선

#47 chore : ⚙️ 네브바 버튼 오류 수정
  src/components/common/NavBar.tsx
Labels: :sparkles: feature, 남준

#48 [#46][FEATURE] #C-12 일간 계획 정보 조회 api 연결
  src/components/Day/TodayNote/TodayNote.tsx
  src/components/Day/TodayNote/TodayNoteSection.tsx
  src/components/Day/TodayPlan/TodayPlanInput.tsx
  src/components/Day/TodayPlan/index.tsx
  src/components/Week/MonthlyGoal/MonthlyGoalInput.tsx
  src/hooks/query/useGetTodayNoteData.tsx
  src/hooks/useDebouncing.tsx
  src/lib/api/api.ts
  src/lib/api/dayApi.ts
  src/types/day.ts
Labels: :sparkles: feature, 희선

#53 [#49] 정보 작성 api 연결
  src/components/Day/DayInfoSection/DayChange.tsx
  src/components/Day/TodayNote/TodayNote.tsx
  src/components/Day/TodayNote/TodayNoteSection.tsx
  src/components/Day/TodayPlan/EmojiPicker.tsx
  src/components/Day/TodayPlan/TodayPlanInput.tsx
  src/components/Day/TodayPlan/index.tsx
  src/components/Week/MonthlyGoal/MonthlyGoalBox.tsx
  src/components/Week/MonthlyGoal/MonthlyGoalInput.tsx
  src/components/Week/WeeklyGoal/WeeklyGoalBox.tsx
  src/components/Week/WeeklyGoal/WeeklyGoalInput.tsx
  src/hooks/query/useGetWeeklyGoalData.tsx
  src/hooks/query/usePostInformationData.tsx
  src/hooks/useDebouncing.tsx
  src/lib/api/dayApi.ts
  src/states/index.ts
  src/types/api.ts
  src/types/day.ts
Labels: :sparkles: feature, 희선

#55 [#44][FEATURE] #C-15 하위계획, 미룬 계획, 일간 계획, 자주 사용하는 계획 패치
  package.json
  src/components/Day/MainDayPlanList.tsx
  src/components/Day/Reschedule.tsx
  src/components/common/DayPlanChip/CommonDayPlanChip.tsx
  src/components/common/DayPlanList/DayPlan.tsx
  src/components/common/DayPlanList/DayPlanList.tsx
  src/components/common/DayPlanList/SubDayPlanList.tsx
  src/components/common/RoutineBox/index.tsx
  src/hooks/query/useGetDelaySchedules.ts
  src/hooks/query/useGetRoutineSchedules.ts
  src/hooks/query/useGetSubSchedules.ts
  src/hooks/query/useGetTodaySchedules.ts
  src/hooks/query/usePatchCompletedSchedules.ts
  src/lib/api/dayApi.ts
  src/states/index.ts
  src/types/day.ts
  src/types/index.ts
  src/utils/getFlagedData.ts
  yarn.lock
Labels: :sparkles: feature, 나희

#58 [#54][FEATURE] #C-15 계획블록 시간 설정, 삭제
  src/components/Day/TimeDragSection/TimeBlock.tsx
  src/components/Day/TimeDragSection/TimeBlockSection.tsx
  src/components/Day/TimeDragSection/TimeBlocks.tsx
  src/hooks/query/usePostScheduleTime.tsx
  src/lib/api/dayApi.ts
  src/types/day.ts
Labels: :sparkles: feature, 희선

#59 [#37][FEATURE] #B-3 주간계획 섹션 제작
  .husky/pre-commit
  public/assets/SmileEmoticon.png
  public/assets/SmileEmoticon.svg
  src/components/Day/TodayNote/TodayNoteSection.tsx
  src/components/Day/TodayPlan/EmojiPicker.tsx
  src/components/Day/TodayPlan/index.tsx
  src/components/Week/WeekChange.tsx
  src/components/Week/WeekPlan/WeekPlan.tsx
  src/components/Week/WeekPlan/WeekPlanCard.tsx
  src/hooks/query/useEmojiListData.tsx
  src/lib/api/dayApi.ts
  src/pages/day/[date].tsx
  src/pages/week/[week].tsx
  src/types/day.ts
Labels: :sparkles: feature, 유림

#65 [#60] [FEATURE] #D-2 일간 계획 페이지 조립
  src/components/Day/DayInfoSection/DayInfo.tsx
  src/components/Day/TimeDragSection/TimeBlockSection.tsx
  src/components/Day/TimeDragSection/TimeLine.tsx
  src/components/Day/TodayNote/TodayNote.tsx
  src/components/Day/TodayPlan/EmojiPicker.tsx
  src/components/Day/TodayPlan/index.tsx
  src/components/common/DayPlanList/DayPlanList.tsx
  src/pages/day/[date].tsx
  src/states/index.ts
  src/styles/Calendar.ts
Labels: :sparkles: feature, 희선

#67 [#66][FEATURE] #C-15 계획블록 시간 설정, 삭제 수정
  src/components/Day/TimeDragSection/TimeBlock.tsx
  src/components/Day/TimeDragSection/TimeBlockSection.tsx
  src/components/Day/TimeDragSection/TimeBlocks.tsx
  src/components/Day/TimeDragSection/TimeLine.tsx
  src/components/common/DayPlanList/DayPlanList.tsx
  src/hooks/query/usePatchScheduleTime.tsx
  src/hooks/useDragBlock.ts
  src/lib/api/dayApi.ts
  src/types/day.ts
Labels: :sparkles: feature, 희선

#69 [#68][FEATURE] #D-3 주간 계획 페이지 조립
  public/assets/DragmeLogo.svg
  src/components/Week/WeekChange.tsx
  src/components/common/NavBar.tsx
  src/pages/day/[date].tsx
  src/pages/week/[week].tsx
Labels: :sparkles: feature, 희선

#75 [#72][HOTFIX] 하루노트 섹션 관련 css 고치기
  src/components/Day/DayPlanModal/SubPlanBox.tsx
  src/components/Day/DayPlanModal/SubPlanTitle.tsx
  src/components/Day/TodayNote/TodayNote.tsx
  src/components/Day/TodayPlan/EmojiPicker.tsx
  src/components/Day/TodayPlan/TodayPlanInput.tsx
Labels: :fire: hotfix, 유림

#83 [#74][FEATURE] #D-4 RoutineRoad 모달 애니메이션 삽입, Favicon 적용 및 404페이지 디자인
  public/assets/404PageError.svg
  public/assets/MyPageModal.png
  public/assets/icons/HamburgerMenu.svg
  public/favicon.ico
  src/components/common/DayPlanList/DayPlanList.tsx
  src/components/common/NavBar.tsx
  src/components/common/RoutineBox/index.tsx
  src/lib/style/animation.ts
  src/pages/404.tsx
  src/pages/day/[date].tsx
  src/pages/week/[week].tsx
  src/states/index.ts
Labels: :sparkles: feature, 남준
