Repository Team-DragMe/DragMe-Client, pull requests merged in 2023-03, with the labels that each got.

#105 [#104] TodayNoteSection 내에 서버 연결 제거하기
  src/components/Day/TodayNote/TodayNote.tsx
  src/components/Day/TodayNote/TodayNoteSection.tsx
  src/components/Day/TodayPlan/EmojiPicker.tsx
  src/components/Day/TodayPlan/TodayPlanInput.tsx
  src/components/common/DayPlanList/DayPlan.tsx
  src/hooks/useDebouncing.tsx
  src/mock-data/todayPlan.ts
Labels: 🚧 refactor, 유림

#107 [#106][REFACTOR] 캘린더, 타임블럭 드래그 부분 서버 삭제
  src/components/Day/CalendarModal/CalendarModal.tsx
  src/components/Day/TimeDragSection/TimeBlockSection.tsx
  src/mock-data/schedules.ts
Labels: 🚧 refactor, 희선

#117 [#114][FEATURE] #114 온보딩 페이지 마크업 수정
  public/assets/StartBtn.svg
  src/components/OnboardingPage/Footer.tsx
  src/components/OnboardingPage/Header.tsx
  src/components/OnboardingPage/Intro.tsx
  src/components/common/NavBar.tsx
  src/pages/day/[date].tsx
  src/pages/index.tsx
Labels: :sparkles: feature, 남준

#118 [#113][HOTFIX] 날짜 변수 로직변경
  src/components/Day/DayInfoSection/DateController.tsx
  src/components/Day/DayInfoSection/DateView.tsx
Labels: :fire: hotfix, 남준
